services:
  - type: web
    name: mini-e-commerce-spa
    env: static
    buildCommand: cd mini-e-commerce-spa && npm install && npm run build
    staticPublishPath: mini-e-commerce-spa/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html